<?php

return [
    'route_prefix' => env('ACCOUNTING_ROUTE_PREFIX', 'accounting'),
    'api_prefix' => env('ACCOUNTING_API_PREFIX', 'api/v1/accounting'),
    'api_middleware' => array_values(array_filter(explode(',', env('ACCOUNTING_API_MIDDLEWARE', 'api,auth:sanctum')))),

    'defaults' => [
        'currency_code' => env('ACCOUNTING_BASE_CURRENCY', 'PKR'),
        'cash_account_code' => env('ACCOUNTING_CASH_ACCOUNT_CODE', '1101'),
        'bank_account_code' => env('ACCOUNTING_BANK_ACCOUNT_CODE', '1102'),
        'retained_earnings_account_code' => env('ACCOUNTING_RETAINED_EARNINGS_ACCOUNT_CODE', '3101'),
        'rounding_account_code' => env('ACCOUNTING_ROUNDING_ACCOUNT_CODE', '5201'),
    ],

    'permissions' => [
        'accounting.view',
        'accounting.manage-settings',
        'account-types.view',
        'account-types.create',
        'account-types.update',
        'account-types.delete',
        'currencies.view',
        'currencies.create',
        'currencies.update',
        'currencies.delete',
        'periods.view',
        'periods.create',
        'periods.update',
        'periods.delete',
        'periods.close',
        'periods.reopen',
        'chart-of-accounts.view',
        'chart-of-accounts.create',
        'chart-of-accounts.update',
        'chart-of-accounts.delete',
        'cost-centers.view',
        'cost-centers.create',
        'cost-centers.update',
        'cost-centers.delete',
        'journal-entries.view',
        'journal-entries.create',
        'journal-entries.update',
        'journal-entries.delete',
        'journal-entries.post',
        'journal-entries.reverse',
        'journal-entries.void',
        'bank-accounts.view',
        'bank-accounts.create',
        'bank-accounts.update',
        'bank-accounts.delete',
        'reconciliations.view',
        'reconciliations.create',
        'reconciliations.update',
        'reconciliations.delete',
        'tax-codes.view',
        'tax-codes.create',
        'tax-codes.update',
        'tax-codes.delete',
        'tax-rates.view',
        'tax-rates.create',
        'tax-rates.update',
        'tax-rates.delete',
        'account-balance-snapshots.view',
        'reports.general-ledger.view',
        'reports.trial-balance.view',
        'reports.balance-sheet.view',
        'reports.income-statement.view',
        'reports.cash-flow.view',
        'reports.aged-receivables.view',
        'reports.aged-payables.view',
        'reports.account-statement.view',
        'audit-logs.view',
    ],

    'roles' => [
        'super-admin' => ['*'],
        'accountant' => [
            'accounting.view',
            'accounting.manage-settings',
            'account-types.view',
            'currencies.view',
            'periods.view',
            'periods.close',
            'chart-of-accounts.view',
            'cost-centers.view',
            'journal-entries.view',
            'journal-entries.create',
            'journal-entries.update',
            'journal-entries.post',
            'journal-entries.reverse',
            'bank-accounts.view',
            'reconciliations.view',
            'tax-codes.view',
            'tax-codes.create',
            'tax-codes.update',
            'tax-rates.view',
            'tax-rates.create',
            'tax-rates.update',
            'account-balance-snapshots.view',
            'reports.general-ledger.view',
            'reports.trial-balance.view',
            'reports.balance-sheet.view',
            'reports.income-statement.view',
            'reports.cash-flow.view',
            'reports.aged-receivables.view',
            'reports.aged-payables.view',
            'reports.account-statement.view',
            'audit-logs.view',
        ],
        'viewer' => [
            'accounting.view',
            'chart-of-accounts.view',
            'journal-entries.view',
            'tax-codes.view',
            'tax-rates.view',
            'account-balance-snapshots.view',
            'reports.general-ledger.view',
            'reports.trial-balance.view',
            'reports.balance-sheet.view',
            'reports.income-statement.view',
            'reports.cash-flow.view',
            'reports.aged-receivables.view',
            'reports.aged-payables.view',
            'reports.account-statement.view',
        ],
    ],
];
